### ISSUE TITLE
IPython tests fail with traitlets master

### ISSUE THREAD

**Issue by takluyver** [ipython/traitlets#176]
Looks like PR #175 broke something:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/testing/iptest.py", line 435, in run_iptest
    globalipapp.start_ipython()
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/testing/globalipapp.py", line 103, in start_ipython
    shell = TerminalInteractiveShell.instance(config=config,
  File "/home/takluyver/.local/lib/python3.4/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 506, in __init__
    self.init_magics()
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/terminal/interactiveshell.py", line 797, in init_magics
    super(TerminalInteractiveShell, self).init_magics()
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 2018, in init_magics
    user_magics=m.UserMagics(self))
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/core/magic.py", line 547, in __init__
    super(Magics, self).__init__(**kwargs)
  File "/home/takluyver/.local/lib/python3.4/site-packages/traitlets/config/configurable.py", line 74, in __init__
    super(Configurable, self).__init__(**kwargs)
  File "/home/takluyver/.local/lib/python3.4/site-packages/traitlets/traitlets.py", line 952, in __init__
    super(HasTraits, self).__init__(*super_args, **super_kwargs)
TypeError: object.__init__() takes no parameters
```

**Comment by minrk** [comment]
#177 makes it a warning instead, so we can be safe for a cycle.
