### ISSUE TITLE
py3compat is still used in traitlets.traitlets, but not imported

### ISSUE THREAD

**Issue by takluyver** [ipython/traitlets#205]
#204 removed the import of `py3compat` from `traitlets.traitlets`, but that is still used, and Jenkins tests are failing:

```
Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/bin/iptest", line 9, in <module>
    load_entry_point('ipython==5.0.0.dev0', 'console_scripts', 'iptest')()
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.core.interactiveshell import DummyMod
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 171, in <module>
    class InteractiveShell(SingletonConfigurable):
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 232, in InteractiveShell
    help="Set the color scheme (NoColor, Linux, or LightBG)."
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/traitlets/traitlets.py", line 2034, in __init__
    values = [py3compat.cast_unicode_py2(value) for value in values]
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/traitlets/traitlets.py", line 2034, in <listcomp>
    values = [py3compat.cast_unicode_py2(value) for value in values]
NameError: name 'py3compat' is not defined
```

Ping @Carreau

**Comment by minrk** [comment]
test coverage!
