### ISSUE TITLE
Cannot use `default_value=None` with `allow_none=true`

### ISSUE THREAD

**Issue by Carreau** [ipython/traitlets#223]
Obviously, because `allow_none` is set after. Still feel ugly to use a `@default` function just for that. 
Maybe a hint somewhere in the docs about a better way to do that ? 
Of if `None` is passed as construction, assume `allow_none=True`, as most of the default values are `traitlets.Undefined` ?

Thoughts ?

**Comment by SylvainCorlay** [comment]
I don't understand the issue. We use `allow_none=True` with `default_value=None` all the time. Do you have an example ?

**Comment by Carreau** [comment]
```
$ cat foo.py ; python foo.py
from traitlets import Enum
from traitlets.config import Configurable

class Foo(Configurable):

    myint = Enum([1,2,3], default_value=None).tag(config=True, allow_none=True)

C = Foo()
Traceback (most recent call last):
  File "foo.py", line 8, in <module>
    C = Foo()
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/traitlets/traitlets.py", line 910, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/traitlets/traitlets.py", line 938, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/traitlets/traitlets.py", line 929, in setup_instance
    value.instance_init(self)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/traitlets/traitlets.py", line 495, in instance_init
    v = self._validate(obj, self.default_value)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/traitlets/traitlets.py", line 564, in _validate
    value = self.validate(obj, value)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/traitlets/traitlets.py", line 2012, in validate
    self.error(obj, value)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/traitlets/traitlets.py", line 598, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'myint' trait of a Foo instance must be any of [1, 2, 3], but a value of None <class 'NoneType'> was specified.
```

**Comment by SylvainCorlay** [comment]
`allow_none=True` is not metadata, it is a kwarg to Enum.

**Comment by Carreau** [comment]
Hum, `tag()` should likely raise a warning is `allow_none` is in one of the kwargs.

**Comment by SylvainCorlay** [comment]
Good idea.
