### ISSUE TITLE
`ValueError: Multiply defined option: hist_file` when running jupyter nbconvert on 5.0.0

### ISSUE THREAD

**Issue by csala** [ipython/traitlets#609]
## Problem Description

After the `traitlets==5.0.0` release, `jupyter nbconvert --execute` crashes with the error `ValueError: Multiply defined option: hist_file` when passing multiple `.ipynb` files as input.

If `traitlets` is downgraded to 4.3.3, everything works fine.

## Steps to reproduce

1. Install `jupyter` and `traitlets==5.0.0`.
2. Create two notebooks. They can be two empty notebooks.
3. Run `jupyter nbconvert --execute` passing the two notebooks or more.
4. The first notebook will run without issues and the second one will crash, no matter the order in which they are run.

```
$ python --version
Python 3.7.8
$ pip freeze | egrep 'traitlets|jupyter'
jupyter==1.0.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-core==4.6.3
traitlets==5.0.0
$ jupyter nbconvert --execute Untitled.ipynb Untitled2.ipynb 
[NbConvertApp] Converting notebook Untitled.ipynb to html
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] Writing 271690 bytes to Untitled.html
[NbConvertApp] Converting notebook Untitled2.ipynb to html
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/config/application.py", line 837, in launch_instance
    app.initialize(argv)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/config/application.py", line 86, in inner
    return method(app, *args, **kwargs)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 582, in initialize
    self.init_kernel()
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 452, in init_kernel
    user_ns=self.user_ns,
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/config/configurable.py", line 510, in instance
    inst = cls(*args, **kwargs)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 68, in __init__
    kernel      = self,
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/config/configurable.py", line 510, in instance
    inst = cls(*args, **kwargs)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 661, in __init__
    self.init_history()
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 1802, in init_history
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/IPython/core/history.py", line 537, in __init__
    **traits)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/IPython/core/history.py", line 214, in __init__
    super(HistoryAccessor, self).__init__(**traits)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/config/configurable.py", line 101, in __init__
    self.config = config
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/traitlets.py", line 602, in __set__
    self.set(obj, value)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/traitlets.py", line 591, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/traitlets.py", line 1220, in _notify_trait
    type='change',
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/traitlets.py", line 1225, in notify_change
    return self._notify_observers(change)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/traitlets.py", line 1262, in _notify_observers
    c(event)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/traitlets.py", line 886, in compatible_observer
    return func(self, change)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/config/configurable.py", line 205, in _config_changed
    self._load_config(change.new, traits=traits, section_names=section_names)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/config/configurable.py", line 168, in _load_config
    config_value = config_value.get_value(traits[name])
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/config/loader.py", line 426, in get_value
    raise ValueError("Multiply defined option: %s" % trait.name)
ValueError: Multiply defined option: hist_file
Traceback (most recent call last):
  File "/home/xals/.virtualenvs/test-traitlets/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/traitlets/config/application.py", line 838, in launch_instance
    app.start()
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 95, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 307, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 403, in preprocess
    with self.setup_preprocessor(nb, resources, km=km):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 345, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(**kwargs)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 296, in start_new_kernel
    kc.wait_for_ready(timeout=self.startup_timeout)
  File "/home/xals/.virtualenvs/test-traitlets/lib/python3.7/site-packages/jupyter_client/blocking/client.py", line 104, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info
```

**Comment by Carreau** [comment]
I think that has been fixed in master that uses nbclient.
This is/was a bug but not in traitlets.

**Comment by rmorshea** [comment]
@Carreau can we close?

**Comment by csala** [comment]
> I think that has been fixed in master that uses nbclient.
> This is/was a bug but not in traitlets.

I'm afraid I am still hitting this, even if I use the master version:

```
$ mkvirtualenv -p $(which python3.7) test-traitlets
$ git clone git@github.com:ipython/traitlets.git traitlets-master
$ cd traitlets-master
$ pip install -e .
$ cd ..
$ pip install jupyter
$ jupyter nbconvert --execute Untitled.ipynb Untitled1.ipynb
... same error as above ...
```

**Comment by minrk** [comment]
@csala I think @Carreau was mentioning that the fixed bug in *nbconvert* master, not traitlets master.

**Comment by csala** [comment]
Oh, my bad. I can confirm that `nbconvert` master fixes it.

Please feel free to close this.
