### ISSUE TITLE
Inheritance, overriding default values, and accessing them through super()

### ISSUE THREAD

**Issue by ypsah** [ipython/traitlets#660]
Hi,

I am trying to subclass `KubeSpawner` from [`jupyter/kubespawner`](https://github.com/jupyter/kubespawner), which uses traitlets extensively, and override the default value of its `options_form` attribute.

Essentially, what I am trying to do boils down to overriding the default value of a traitlet from a child class while still using the default from the parent class:

```python
from traitlets import default, HasTraits, Int

class A(HasTraits):
    param = Int()

    @default('param')
    def _param(self):
        return 1

class B(A):

    @default('param')
    def _param(self):
        return super().param + 1

assert B().param == 2
```

This does not work and raises a `RecursionError`:

```
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'param'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'param'

During handling of the above exception, another exception occurred:
(...)
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    assert B().param == 1
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 1578, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 975, in __call__
    return self.func(*args, **kwargs)
  File "test.py", line 16, in _param
    return super().param + 1
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 1578, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 975, in __call__
    return self.func(*args, **kwargs)
  File "test.py", line 16, in _param
    return super().param + 1
(...)
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "/Users/user/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/traitlets/traitlets.py", line 1573, in trait_defaults
    if not self.has_trait(n):
RecursionError: maximum recursion depth exceeded
```

Is inheritance explicitely not supported for traitlets?
Am I, or is `KubeSpawner` using traitlets incorrectly?
Can you think of a fix or a workaround?

Cheers!

**Comment by rmorshea** [comment]
The solution here is to use `super()._param()` instead.

This does feel like a bug to me though. I'll try and investigate what's going on.

**Comment by rmorshea** [comment]
Ok, so correct way to do this is definitely to use `super()._param()`. To demonstrate why, consider this code example that demonstrates the form of the problem.

```python
class MyClass:

    _default_generators = {"my_prop": "_my_prop_default"}

    @property
    def my_prop(self):
        default_method_name = self._default_generators["my_prop"]
        default_method = getattr(self, default_method_name)
        return default_method()

    def _my_prop_default(self):
        return 1


class MyChildClass(MyClass):

    def _my_prop_default(self):
        return super().my_prop + 1


assert MyChildClass().my_prop == 2
```

The code above produces a similar recursion error because (as in `traitlets`), the default generator is being looked up by name, rather than by reference.

Looking up by name, rather than be reference was a design decision that makes sub-classing simpler on other situations.

**Comment by ypsah** [comment]
Fair enough. This seems unintuitive to me, as it means that I will have to rely on accessing a "private" method, but thank you for taking the time to answer. Cheers! :+1:

**Comment by rmorshea** [comment]
This is definitely a bit confusing for newcomers since it doesn't really map onto how you would normally do this with `@property`.

With that said, the public private distinction usually only applies to the object's callers, not its own methods. The explicit method call is also probably a bit more understandable since the attribute access pattern would require indirection through the `traitlets` framework that other readers might not be privy to.
