### ISSUE TITLE
Maximum recursion limit exceed when using same class at different positions in the hierarchy

### ISSUE THREAD

**Issue by maxnoe** [ipython/traitlets#704]
The following code raises a `MaximumRecursionDepthExceeded` error:

```python

from traitlets.config import Configurable
from traitlets import Int


class Child(Configurable):
    value = Int(default_value=1).tag(config=True)


class Parent(Configurable):
    classes = [Child]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.child = Child(parent=self)


class GrandParent(Configurable):
    classes = [Parent]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.parent = Parent(parent=self)
        self.child = Child(parent=self)


gp = GrandParent()
```

Error:

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    gp = GrandParent()
  File "test.py", line 23, in __init__
    self.child = Child(parent=self)
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/config/configurable.py", line 107, in __init__
    self.config = config
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/traitlets.py", line 606, in __set__
    self.set(obj, value)
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/traitlets.py", line 595, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/traitlets.py", line 1219, in _notify_trait
    self.notify_change(Bunch(
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/traitlets.py", line 1229, in notify_change
    return self._notify_observers(change)
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/traitlets.py", line 1266, in _notify_observers
    c(event)
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/traitlets.py", line 890, in compatible_observer
    return func(self, change)
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/config/configurable.py", line 211, in _config_changed
    self._load_config(change.new, traits=traits, section_names=section_names)
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/config/configurable.py", line 161, in _load_config
    my_config = self._find_my_config(cfg)
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/config/configurable.py", line 143, in _find_my_config
    cfgs.append(self.parent._find_my_config(cfg))
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/config/configurable.py", line 143, in _find_my_config
    cfgs.append(self.parent._find_my_config(cfg))
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/config/configurable.py", line 143, in _find_my_config
    cfgs.append(self.parent._find_my_config(cfg))
  [Previous line repeated 982 more times]
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/config/configurable.py", line 142, in _find_my_config
    if self.parent:
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/traitlets/traitlets.py", line 577, in __get__
    return self.get(obj, cls)
RecursionError: maximum recursion depth exceeded
```

**Comment by maxnoe** [comment]
Switching the order of `Parent` and `Child` in `GrandParent.__init__` works as expected:

```
from traitlets.config import Configurable, Config
from traitlets import Int


class Child(Configurable):
    value = Int(default_value=1).tag(config=True)


class Parent(Configurable):
    classes = [Child]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.child = Child(parent=self)


class GrandParent(Configurable):
    classes = [Parent]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.child = Child(parent=self)
        self.parent = Parent(parent=self)


config = Config()
config.GrandParent.Child.value = 10
config.GrandParent.Parent.Child.value = 9

gp = GrandParent(config=config)
print(gp.child.value)
print(gp.parent.child.value)

```

prints
```
10
9
```

**Comment by vidartf** [comment]
Did you mean to make a "parent" loop: `self.parent = Parent(parent=self)` ? Won't these two instances now be each other's parents? I think the use of `parent` in traitlets assume the graph they form are not cyclic.

**Comment by maxnoe** [comment]
Ah, dam, sorry, yes! I did not mean override the traitlets pre-defined `parent`, of couse!

Not calling the instance of `Parent` `parent` works perfectly fine:

```python

from traitlets.config import Configurable
from traitlets import Int


class Child(Configurable):
    value = Int(default_value=1).tag(config=True)


class Parent(Configurable):
    classes = [Child]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.child = Child(parent=self)


class GrandParent(Configurable):
    classes = [Parent]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.parent_ = Parent(parent=self)
        self.child = Child(parent=self)


gp = GrandParent()
print(gp.parent_.child.value)
print(gp.child.value)

```
