### ISSUE TITLE
AssertionError in traitlets-5.2.2

### ISSUE THREAD

**Issue by cgranade** [ipython/traitlets#740]
As of traitlets-5.2.2, packages that depend on traitlets (e.g.: the `jupyter` CLI tool) raise assertion errors when importing the `traitlets` package:

```
Traceback (most recent call last):
  File "C:\Miniconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Miniconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda\Scripts\jupyter-kernelspec.EXE\__main__.py", line 4, in <module>
  File "C:\Miniconda\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Miniconda\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
    from traitlets.config import LoggingConfigurable
  File "C:\Miniconda\lib\site-packages\traitlets\__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "C:\Miniconda\lib\site-packages\traitlets\_version.py", line 7, in <module>
    assert __version__ == (
AssertionError
```

**Comment by FlipperPA** [comment]
This is because the version in the package includes a `.final` appended so it doesn't match the string of the version number. Is this assertion check of the version being too clever by half?

**Comment by JanB1** [comment]
Related Pull Request: #739
