### ISSUE TITLE
Traitets fail to load - Version 5.2.2 AssertionError

### ISSUE THREAD

**Issue by Joffreybvn** [ipython/traitlets#741]
Hello,

I just installed Jupyter. Traitlets comes as dependency of it, and I'm getting the following error:
```python
Traceback (most recent call last):
  File "/home/joffrey/.pyenv/versions/3.9.7/envs/recorder-orchestrator/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/joffrey/.pyenv/versions/recorder-orchestrator/lib/python3.9/site-packages/notebook/__init__.py", line 27, in <module>
    from .nbextensions import install_nbextension
  File "/home/joffrey/.pyenv/versions/recorder-orchestrator/lib/python3.9/site-packages/notebook/nbextensions.py", line 23, in <module>
    from .config_manager import BaseJSONConfigManager
  File "/home/joffrey/.pyenv/versions/recorder-orchestrator/lib/python3.9/site-packages/notebook/config_manager.py", line 12, in <module>
    from traitlets.config import LoggingConfigurable
  File "/home/joffrey/.pyenv/versions/recorder-orchestrator/lib/python3.9/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/home/joffrey/.pyenv/versions/recorder-orchestrator/lib/python3.9/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError
```

- It seems that the assert **line 7** of `_version.py` fails.
- `__version__` should be equal to `"5.2.2.final"`. I fixed it locally and created a PR

**Comment by rgs258** [comment]
whoa, this blew up [nbformat](https://github.com/jupyter/nbformat)

**Comment by MrVPlusOne** [comment]
This also caused VSCode to print out a misleading error "Running cells with 'Python 3.10.4 ('py3.10')' requires ipykernel package."...

**Comment by JanB1** [comment]
@jakevdp @lostella @rgs258 @MrVPlusOne @jnm @MichaelBroughton
Fix implemented by @Joffreybvn and @wholtz, see #739.
Should be good now.

**Comment by jsmith2021Brandeis** [comment]
I am also getting an Assertion Error installing this version

**Comment by rcramblit** [comment]
This is fixed for us with the `5.2.2.post1` release. Thank you for the quick and easy fix!
