### ISSUE TITLE
5.2.2: sphinx fails

### ISSUE THREAD

**Issue by kloczek** [ipython/traitlets#742]
Looks like in just released 5.2.2 sphinx fails
```console
[tkloczko@devel-g2v traitlets-5.2.2]$ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v4.5.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/traitlets-5.2.2/docs/source/conf.py", line 28, in <module>
    exec(
  File "../../traitlets/_version.py", line 7, in <module>
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 345, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/traitlets-5.2.2/docs/source/conf.py", line 28, in <module>
    exec(
  File "../../traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/traitlets-5.2.2/docs/source/conf.py", line 28, in <module>
    exec(
  File "../../traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError
```

**Comment by kloczek** [comment]
gentle ping ..
