### ISSUE TITLE
One test fails

### ISSUE THREAD

**Issue by yurivict** [ipython/traitlets#866]
```
========================================================================================= FAILURES ==========================================================================================
______________________________________________________________________ TestForwardDeclaredTypeTrait.test_default_value ______________________________________________________________________

self = <traitlets.tests.test_traitlets.TestForwardDeclaredTypeTrait testMethod=test_default_value>

    def test_default_value(self):
        if hasattr(self, "_default_value"):
>           self.assertEqual(self._default_value, self.obj.value)  # type:ignore
E           AssertionError: None != <class 'traitlets.tests.test_traitlets.ForwardDeclaredBar'>

traitlets/tests/test_traitlets.py:1261: AssertionError
============================================================================== 1 failed, 565 passed in 17.58s ===============================================================================
*** Error code 1
```

Version: 5.10.0
Python-3.9
FreeBSD 13.2

**Comment by shiv-planetrics** [comment]
Not sure if the following error stacktrace is related to this issue. This occurred when I was trying to run Jupyter notebook in a container. `notebook` package version `6.5.5`.
```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/jupyter_core/application.py", line 285, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/venv/lib/python3.8/site-packages/traitlets/config/application.py", line 1044, in launch_instance
    app = cls.instance(**kwargs)
  File "/venv/lib/python3.8/site-packages/traitlets/config/configurable.py", line 555, in instance
    inst = cls(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/traitlets/traitlets.py", line 1295, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/traitlets/traitlets.py", line 1338, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/traitlets/traitlets.py", line 1314, in setup_instance
    init(self)
  File "/venv/lib/python3.8/site-packages/notebook/traittypes.py", line 226, in instance_init
    self._resolve_classes()
  File "/venv/lib/python3.8/site-packages/notebook/traittypes.py", line 238, in _resolve_classes
    warn(f"{klass} is not importable. Is it installed?", ImportWarning)
TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'
```

**Comment by didickman** [comment]
I came here looking for this same exception. We see the same exception on openbsd where we just updated to traitlets 5.10 and now notebook 6.3.0 won’t start. On OpenBSD there is also a message about jupyter_server being missing.

Either downgrading to traitlets 5.9 or downgrading to notebook 6.2.0 fixes things on our end.

Not sure what is the correct fix though.

**Comment by yurivict** [comment]
5.14.1 doesn't have test failures.
